services:
  server:
    build: ./social_network
    working_dir: /var/www/server
    volumes:
      - ./social_network/:/var/www/server/
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
       - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
